name: Design spec 💄
description: Describe design requirements.
labels: ['design']
body:
  - type: textarea
    attributes:
      label: Description
      description: Description of the project. What is the problem you’re trying to solve? Include any contextual links.
  - type: textarea
    attributes:
      label: Audience
      description: Who does this affect? Who will determine if this is successful (stakeholders)?
  - type: textarea
    attributes:
      label: Goals
      description: What is the purpose of this project? What are users/we getting out of this?
  - type: textarea
    attributes:
      label: Metrics
      description: How is success defined for this project? Are there specific KPIs tied to it?
  - type: textarea
    attributes:
      label: Timeline
      description: When is this due? Working backwards from there, include dates for a few drafts and feedback cycles
  - type: textarea
    attributes:
      label: Specs
      description: What are the constraints, sizes, etc? Include any links to spec sheets or detail pages.
